name: Event
description: Create a new event
title: 'Event Title'
labels: ['Event :sparkles:']
body:
  - type: markdown
    attributes:
      value: |
        Hey there :wave:. We're using [GitEvents](http://gitevents.org) to manage events based on issues. There's still some work to be done, so please make sure you stick to the formatting of dates for the time being.
  - type: textarea
    id: description
    attributes:
      label: Event Description
      description: A concise description
    validations:
      required: true
  - type: input
    id: location
    attributes:
      label: Location
      description: Location ID (locations.json) or String
      placeholder: 'hugge-paphos'
    validations:
      required: true
  - type: input
    id: startDate
    attributes:
      label: Date
      description: Start Date
      placeholder: '31.03.2022'
    validations:
      required: true
  - type: input
    id: startTime
    attributes:
      label: Time
      description: Start time
      placeholder: '18.30'
    validations:
      required: true
  - type: input
    id: duration
    attributes:
      label: Duration
      description: Duration
      placeholder: '1h30m'
    validations:
      required: true
  - type: checkboxes
    id: code-of-conduct
    attributes:
      label: Code of Conduct
      description:
        The Code of Conduct helps create a safe space for everyone. We require
        that everyone agrees to it.
      options:
        - label:
            I agree to follow this project's [Code of
            Conduct](https://berlincodeofconduct.org)
          required: true
