name: Create Events on Discord & Twitter

on:
  issues:
    types: [labeled]

jobs:
  discord:
    if: contains( github.event.issue.labels.*.name, 'Approved' )
    uses: gitevents/propaganda/.github/workflows/discord-event.yml@main
    with:
      server-id: "855088264180400198"
      time-zone: 'Europe/Nicosia'
  create-issue-tweet:
    uses: ./.github/workflows/create-issue-tweet.yml
  tweet-issue:
    needs: [create-issue-tweet]
    uses: gitevents/propaganda/.github/workflows/twitter-event.yml@main
    with:
      status: ${{ needs.create-issue-tweet.outputs.tweet }}
    secrets:
      consumer-key: ${{ secrets.TWITTER_CONSUMER_KEY }}
      consumer-secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
      access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}