name: prepare-micropost

on:
  workflow_call:
    outputs:
      post:
        value: ${{ jobs.prepare.outputs.post }}

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      post: ${{ steps.prepare.outputs.result }}
    steps:
      - name: Create Post
        uses: actions/github-script@v7
        id: prepare
        with:
          result-encoding: string
          script: |
            const {issue} = context.payload
            const getAuthor = issue => issue?.user?.login
            const getIssueLink = issue => issue?.html_url
            const getTitle = issue => issue?.title
            const getContent = (title, author, link) =>
              `New Event: ${title} by ${author}. More information & signup here: ${link}`

            const issueLink = getIssueLink(issue)
            const author = getAuthor(issue)
            const title = getTitle(issue)
            return getContent(title, author, issueLink)
